### ISSUE TITLE
Inquiry about the scale_range

### ISSUE THREAD

**Issue by RayYoh** [YkiWu/EmbodiedOcc#2]
Hi authors, thanks for your great work. I see that most of the implementation code is based on GaussianFormer. However, I find one critical difference in the [range of scale](https://github.com/YkiWu/EmbodiedOcc/blob/657d612dd2b3aee04510d66a8565d74315f6eb9a/config/train_embodied_config.py#L28). Usually how to determine the range?

**Comment by YkiWu** [comment]
> Hi authors, thanks for your great work. I see that most of the implementation code is based on GaussianFormer. However, I find one critical difference in the [range of scale](https://github.com/YkiWu/EmbodiedOcc/blob/657d612dd2b3aee04510d66a8565d74315f6eb9a/config/train_embodied_config.py#L28). Usually how to determine the range?

Scale_range is strongly associated with the size of the whole scene. It directly determines the influence range of each Gaussian. A reasonable setting of this parameter leads to a moderate number of Gaussians used to represent each scene and high accuracy of the final occupancy prediction.

**Comment by RayYoh** [comment]
Got that. Thanks!
