### ISSUE TITLE
Questions about DepthAnythingV2

### ISSUE THREAD

**Issue by Skyyoung226** [YkiWu/EmbodiedOcc#3]
Traceback (most recent call last):
  File "train_mono.py", line 314, in <module>
    main(args)
  File "train_mono.py", line 80, in main
    my_model = build_model(cfg.model)
  File "/EmbodiedOcc/model/__init__.py", line 13, in build_model
    model = build_from_cfg(model_config, MODELS)
  File "/miniconda3/envs/embodiedocc/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/EmbodiedOcc/model/segmentor/gaussian_segmentor/gaussian_segmentor.py", line 51, in __init__
    self.depthanything = DepthAnythingV2(**{**model_configs['vitb'], 'max_depth':20})
TypeError: __init__() got an unexpected keyword argument 'max_depth'

It seems that the init function has been changed? Could you please give the specific change in this model. Thanks a lot!

**Comment by YkiWu** [comment]
> Traceback (most recent call last): File "train_mono.py", line 314, in main(args) File "train_mono.py", line 80, in main my_model = build_model(cfg.model) File "/EmbodiedOcc/model/**init**.py", line 13, in build_model model = build_from_cfg(model_config, MODELS) File "/miniconda3/envs/embodiedocc/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg obj = obj_cls(**args) # type: ignore File "/EmbodiedOcc/model/segmentor/gaussian_segmentor/gaussian_segmentor.py", line 51, in init self.depthanything = DepthAnythingV2(**{**model_configs['vitb'], 'max_depth':20}) TypeError: **init**() got an unexpected keyword argument 'max_depth'
> 
> It seems that the init function has been changed? Could you please give the specific change in this model. Thanks a lot!

All changes in the DepthAnythingV2 are detailed in item 5 of [installation.md](https://github.com/YkiWu/EmbodiedOcc/blob/main/docs/installation.md). You can reconfigure this model according to the instructions here. It seems that the issue might be related to the version of the DepthAnything-V2 being used. Make sure to use the model under Depth-Anything-V2/metric_depth/depth_anything_v2/dpt.py.

**Comment by Skyyoung226** [comment]
Thanks a lot! I have solved this problem!
